#!/usr/bin/env bash
# This script is infinite and has a signal

sigterm_handler(){
    echo '"I am invincible!!!"' 15
    exit 0
}

trap 'sigterm_handler' SIGTERM

while true
do
    echo "to infinity and beyond"
    sleep 2
done
