#!/usr/bin/env bash
# This script is displaying "Best School" 10 times adn hi at 8th
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
