#!/usr/bin/env bash
# This script is displaying "Best School" 10 times adn hi at 8th
for ((i = 1; i <= 10; i++))
do
    if [ $i -ne 8 ]; then
        echo "Best School"
    else
        echo "Hi"
    fi
done
