#!/usr/bin/env bash
# This script is displaying different messages at different times
counter=1

while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luch"
    else
        echo "Best School"
    fi

    ((counter++))
done
