#!/usr/bin/env bash
# This script displsys the time for 12 hours and 59 mins

hour=0
while [ $hour -le 12 ]
do
	echo Hour: $hour
	minute=1
	while [ $minute -le 59 ]
	do
		echo $minute
		(( minutes+= 1 ))
	done

	(( hour+= 1 ))
done
