#!/usr/bin/env bash
# This script displsys the time for 12 hours and 59 mins

hours=0
while [ $hours -le 12 ]
do
	echo Hour: $hours
	minutes=1
	while [ $minutes -le 59 ]
	do
		echo $minutes
		(( minutes+= 1 ))
	done

	(( hour+= 1 ))
done
